#####################################
#                                   #
#    Regular Expression Parser 2    #
#                                   #
#####################################

include ../../Makedef

THE_TARGET= demo

all:
	$(CC) demo.cpp
	$(LINK_TARGET)	demo.o -lmad

clean:
	rm -f *.o
	rm -f *.a
	rm -f *~
